---
#
# The network connection profile provides client applications the information about the target
# blockchain network that are necessary for the applications to interact with it. These are all
# knowledge that must be acquired from out-of-band sources. This file provides such a source.
#
name: "balance-transfer"

#
# Any properties with an "x-" prefix will be treated as application-specific, exactly like how naming
# in HTTP headers or swagger properties work. The SDK will simply ignore these fields and leave
# them for the applications to process. This is a mechanism for different components of an application
# to exchange information that are not part of the standard schema described below. In particular,
# the "x-type" property with the "hlfv1" value example below is used by Hyperledger Composer to
# determine the type of Fabric networks (v0.6 vs. v1.0) it needs to work with.
#
x-type: "hlfv1"

#
# Describe what the target network is/does.
#
description: "Balance Transfer Network"

#
# Schema version of the content. Used by the SDK to apply the corresponding parsing rules.
#
version: "1.0"

#
# The client section will be added on a per org basis see org1.yaml and org2.yaml
#
#client:

#
# [Optional]. But most apps would have this section so that channel objects can be constructed
# based on the content below. If an app is creating channels, then it likely will not need this
# section.
#
channels:
  # name of the channel
  yhchannel:
    # Required. list of orderers designated by the application to use for transactions on this
    # channel. This list can be a result of access control ("org1" can only access "ordererA"), or
    # operational decisions to share loads from applications among the orderers.  The values must
    # be "names" of orgs defined under "organizations/peers"
    orderers:
      - orderer.example.com

    # Required. list of peers from participating orgs
    peers:
      peer0.org1.example.com:
        # [Optional]. will this peer be sent transaction proposals for endorsement? The peer must
        # have the chaincode installed. The app can also use this property to decide which peers
        # to send the chaincode install request. Default: true
        endorsingPeer: true

        # [Optional]. will this peer be sent query proposals? The peer must have the chaincode
        # installed. The app can also use this property to decide which peers to send the
        # chaincode install request. Default: true
        chaincodeQuery: true

        # [Optional]. will this peer be sent query proposals that do not require chaincodes, like
        # queryBlock(), queryTransaction(), etc. Default: true
        ledgerQuery: true

        # [Optional]. will this peer be the target of the SDK's listener registration? All peers can
        # produce events but the app typically only needs to connect to one to listen to events.
        # Default: true
        eventSource: true

      peer1.jywy.trace.com:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

      peer0.yh.trace.cn:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1.yh.trace.cn:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

      peer0.zfjg.gov.cn:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1.zfjg.gov.cn:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

    # [Optional]. what chaincodes are expected to exist on this channel? The application can use
    # this information to validate that the target peers are in the expected state by comparing
    # this list with the query results of getInstalledChaincodes() and getInstantiatedChaincodes()
    chaincodes:
      # the format follows the "cannonical name" of chaincodes by fabric code
      - turbot:v0

#
# list of participating organizations in this network
#
organizations:
  JYWY:
    mspid: JYWYMSP

    peers:
      - peer0.jywy.trace.com
      - peer1.jywy.trace.com

    # [Optional]. Certificate Authorities issue certificates for identification purposes in a Fabric based
    # network. Typically certificates provisioning is done in a separate process outside of the
    # runtime network. Fabric-CA is a special certificate authority that provides a REST APIs for
    # dynamic certificate management (enroll, revoke, re-enroll). The following section is only for
    # Fabric-CA servers.
    certificateAuthorities:
      - ca.jywy.trace.com

    # [Optional]. If the application is going to make requests that are reserved to organization
    # administrators, including creating/updating channels, installing/instantiating chaincodes, it
    # must have access to the admin identity represented by the private key and signing certificate.
    # Both properties can be the PEM string or local path to the PEM file. Note that this is mainly for
    # convenience in development mode, production systems should not expose sensitive information
    # this way. The SDK should allow applications to set the org admin identity via APIs, and only use
    # this route as an alternative when it exists.
    adminPrivateKey:
      path: yhartifacts/channel/crypto-config/peerOrganizations/jywy.trace.com/users/Admin@jywy.trace.com/msp/keystore/efa20ad0a0862ee4e6af67a44eaa16085105095fae23d301a56fd1c48a89f2e0_sk
    signedCert:
      path: yhartifacts/channel/crypto-config/peerOrganizations/jywy.trace.com/users/Admin@jywy.trace.com/msp/signcerts/Admin@jywy.trace.com-cert.pem

  # the profile will contain public information about organizations other than the one it belongs to.
  # These are necessary information to make transaction lifecycles work, including MSP IDs and
  # peers with a public URL to send transaction proposals. The file will not contain private
  # information reserved for members of the organization, such as admin key and certificate,
  # fabric-ca registrar enroll ID and secret, etc.
  YH:
    mspid: YHMSP
    peers:
      - peer0.yh.trace.cn
      - peer1.yh.trace.cn
    certificateAuthorities:
      - ca.yh.trace.cn
    adminPrivateKey:
      path: yhartifacts/channel/crypto-config/peerOrganizations/yh.trace.cn/users/Admin@yh.trace.cn/msp/keystore/f3978f1fd3b0925c9a3453511db647d1c07127cff728afebaa64bf8f96852173_sk
    signedCert:
      path: yhartifacts/channel/crypto-config/peerOrganizations/yh.trace.cn/users/Admin@yh.trace.cn/msp/signcerts/Admin@yh.trace.cn-cert.pem

  ZFJG:
    mspid: ZFJGMSP
    peers:
      - peer0.zfjg.gov.cn
      - peer1.zfjg.gov.cn
    certificateAuthorities:
      - ca.zfjg.gov.cn
    adminPrivateKey:
      path: yhartifacts/channel/crypto-config/peerOrganizations/zfjg.gov.cn/users/Admin@zfjg.gov.cn/msp/keystore/4461e351010434d4b9e08689f8fcd6a1cff65d7c32ef87bee5ba62e4a4d5457b_sk
    signedCert:
      path: yhartifacts/channel/crypto-config/peerOrganizations/zfjg.gov.cn/users/Admin@zfjg.gov.cn/msp/signcerts/Admin@zfjg.gov.cn-cert.pem

#
# List of orderers to send transaction and channel create/update requests to. For the time
# being only one orderer is needed. If more than one is defined, which one get used by the
# SDK is implementation specific. Consult each SDK's documentation for its handling of orderers.
#
orderers:
  orderer.example.com:
    url: grpcs://localhost:7050

    # these are standard properties defined by the gRPC library
    # they will be passed in as-is to gRPC client constructor
    grpcOptions:
      ssl-target-name-override: orderer.example.com

    tlsCACerts:
      path: yhartifacts/channel/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt

#
# List of peers to send various requests to, including endorsement, query
# and event listener registration.
#
peers:
  peer0.jywy.trace.com:
    # this URL is used to send endorsement and query requests
    url: grpcs://localhost:7051

    # this URL is used to connect the EventHub and registering event listeners
    eventUrl: grpcs://localhost:7053

    grpcOptions:
      ssl-target-name-override: peer0.jywy.trace.com
    tlsCACerts:
      path: yhartifacts/channel/crypto-config/peerOrganizations/jywy.trace.com/peers/peer0.jywy.trace.com/tls/ca.crt

  peer1.jywy.trace.com:
    url: grpcs://localhost:7056
    eventUrl: grpcs://localhost:7058
    grpcOptions:
      ssl-target-name-override: peer1.jywy.trace.com
    tlsCACerts:
      path: yhartifacts/channel/crypto-config/peerOrganizations/jywy.trace.com/peers/peer1.jywy.trace.com/tls/ca.crt

  peer0.yh.trace.cn:
    url: grpcs://localhost:8051
    eventUrl: grpcs://localhost:8053
    grpcOptions:
      ssl-target-name-override: peer0.yh.trace.cn
    tlsCACerts:
      path: yhartifacts/channel/crypto-config/peerOrganizations/yh.trace.cn/peers/peer0.yh.trace.cn/tls/ca.crt

  peer1.yh.trace.cn:
    url: grpcs://localhost:8056
    eventUrl: grpcs://localhost:8058
    grpcOptions:
      ssl-target-name-override: peer1.yh.trace.cn
    tlsCACerts:
      path: yhartifacts/channel/crypto-config/peerOrganizations/yh.trace.cn/peers/peer1.yh.trace.cn/tls/ca.crt

  peer0.zfjg.gov.cn:
    url: grpcs://localhost:9051
    eventUrl: grpcs://localhost:9053
    grpcOptions:
      ssl-target-name-override: peer0.zfjg.gov.cn
    tlsCACerts:
      path: yhartifacts/channel/crypto-config/peerOrganizations/zfjg.gov.cn/peers/peer0.zfjg.gov.cn/tls/ca.crt

  peer1.zfjg.gov.cn:
    url: grpcs://localhost:9056
    eventUrl: grpcs://localhost:9058
    grpcOptions:
      ssl-target-name-override: peer1.zfjg.gov.cn
    tlsCACerts:
      path: yhartifacts/channel/crypto-config/peerOrganizations/zfjg.gov.cn/peers/peer1.zfjg.gov.cn/tls/ca.crt

#
# Fabric-CA is a special kind of Certificate Authority provided by Hyperledger Fabric which allows
# certificate management to be done via REST APIs. Application may choose to use a standard
# Certificate Authority instead of Fabric-CA, in which case this section would not be specified.
#
certificateAuthorities:
  ca.jywy.trace.com:
    url: https://localhost:7054
    # the properties specified under this object are passed to the 'http' client verbatim when
    # making the request to the Fabric-CA server
    httpOptions:
      verify: false
    tlsCACerts:
      path: yhartifacts/channel/crypto-config/peerOrganizations/jywy.trace.com/ca/ca.jywy.trace.com-cert.pem

    # Fabric-CA supports dynamic user enrollment via REST APIs. A "root" user, a.k.a registrar, is
    # needed to enroll and invoke new users.
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca.jywy.trace.com

  ca.yh.trace.cn:
    url: https://localhost:8054
    httpOptions:
      verify: false
    tlsCACerts:
      path: yhartifacts/channel/crypto-config/peerOrganizations/yh.trace.cn/ca/ca.yh.trace.cn-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca.yh.trace.cn

  ca.zfjg.gov.cn:
    url: https://localhost:9054
    httpOptions:
      verify: false
    tlsCACerts:
      path: yhartifacts/channel/crypto-config/peerOrganizations/zfjg.gov.cn/ca/ca.zfjg.gov.cn-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca.zfjg.gov.cn
    
