NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.yh.trace.cn-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.yh.trace.cn-cert.pem
    OrganizationalUnitIdentifier: peer
