NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.zfjg.gov.cn-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.zfjg.gov.cn-cert.pem
    OrganizationalUnitIdentifier: peer
